In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**data**

In [2]:
df = pd.read_csv('breast-cancer.csv')

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

**we have categorical data in diagonasis column,so we have to convert them into numerical data**

In [6]:
df['diagnosis'] = df['diagnosis'].map({'M':0,'B':1}).astype(int)


In [7]:
df.sample(10)

id  diagnosis  radius_mean  texture_mean  perimeter_mean  \
125      86561          1       13.850         17.21           88.44   
275    8911164          1       11.890         17.36           76.20   
243   88411702          1       13.750         23.77           88.54   
410     905502          1       11.360         17.57           72.49   
553     924342          1        9.333         21.94           59.01   
161    8711803          0       19.190         15.94          126.30   
401     904647          1       11.930         10.91           76.14   
244     884180          0       19.400         23.50          129.10   
213  881094802          0       17.420         25.56          114.50   
272    8910988          0       21.750         20.99          147.30   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
125      588.7          0.08785           0.06136         0.01420   
275      435.6          0.12250           0.07210         0.05929   
243      590.0          0.08043           0.06807         0.04697   
410      399.8          0.08858           0.05313         0.02783   
553      264.0          0.09240           0.05605         0.03996   
161     1157.0          0.08694           0.11850         0.11930   
401      442.7          0.08872           0.05242         0.02606   
244     1155.0          0.10270           0.15580         0.20490   
213      948.0          0.10060           0.11460         0.16820   
272     1491.0          0.09401           0.19610         0.21950   

     concave points_mean  ...  texture_worst  perimeter_worst  area_worst  \
125              0.01141  ...          23.58           100.30       725.9   
275              0.07404  ...          18.99            79.46       472.4   
243              0.02344  ...          26.34            98.00       706.0   
410              0.02100  ...          36.32            85.07       521.3   
553              0.01282  ...          25.05            62.86       295.8   
161              0.09667  ...          17.81           146.60      1495.0   
401              0.01796  ...          20.14            87.64       589.5   
244              0.08886  ...          30.53           144.90      1417.0   
213              0.06597  ...          28.07           120.40      1021.0   
272              0.10880  ...          28.18           195.90      2384.0   

     smoothness_worst  compactness_worst  concavity_worst  \
125           0.11570            0.13500          0.08115   
275           0.13590            0.08368          0.07153   
243           0.09368            0.14420          0.13590   
410           0.14530            0.16220          0.18110   
553           0.11030            0.08298          0.07993   
161           0.11240            0.20160          0.22640   
401           0.13740            0.15750          0.15140   
244           0.14630            0.29680          0.34580   
213           0.12430            0.17930          0.28030   
272           0.12720            0.47250          0.58070   

     concave points_worst  symmetry_worst  fractal_dimension_worst  \
125               0.05104          0.2364                  0.07182   
275               0.08946          0.2220                  0.06033   
243               0.06106          0.2663                  0.06321   
410               0.08698          0.2973                  0.07745   
553               0.02564          0.2435                  0.07393   
161               0.17770          0.2443                  0.06251   
401               0.06876          0.2460                  0.07262   
244               0.15640          0.2920                  0.07614   
213               0.10990          0.1603                  0.06818   
272               0.18410          0.2833                  0.08858   

     Unnamed: 32  
125          NaN  
275          NaN  
243          NaN  
410          NaN  
553          NaN  
161          NaN  
401          NaN  
244          NaN

**as id and unnamed columns are useless,we can remove them**

In [8]:
df=df.drop(['id','Unnamed: 32'],axis=1)
df.head(3)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          0        17.99         10.38           122.8     1001.0   
1          0        20.57         17.77           132.9     1326.0   
2          0        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   
1         0.1812  ...         24.99          23.41            158.8   
2         0.2069  ...         23.57          25.53            152.5   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  

[3 rows x 31 columns]

**splitting data**

In [9]:
X = df.iloc[: ,1:]
y = df.iloc[: ,0]


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=54)
len(x_test)


114

**introducing algorithm**

In [11]:
from sklearn.neighbors import KNeighborsClassifier
cls=KNeighborsClassifier()

In [12]:
cls.fit(x_train,y_train)

KNeighborsClassifier()

**testing model with trained data**

In [13]:
y_train_pred=cls.predict(x_train)
len(y_train_pred)

455

In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score


In [15]:
confusion_matrix(y_train,y_train_pred)

array([[156,  18],
       [ 10, 271]])

In [16]:
accuracy_score(y_train,y_train_pred)

0.9384615384615385

In [17]:
cls.score(x_train,y_train)

0.9384615384615385

**testing model with test data**

In [18]:
y_test_pred = cls.predict(x_test)

In [19]:
confusion_matrix(y_test,y_test_pred)

array([[36,  2],
       [ 4, 72]])

In [20]:
accuracy_score(y_test,y_test_pred)

0.9473684210526315

In [21]:
cls.score(x_test,y_test)

0.9473684210526315

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.90      0.95      0.92        38
           1       0.97      0.95      0.96        76

    accuracy                           0.95       114
   macro avg       0.94      0.95      0.94       114
weighted avg       0.95      0.95      0.95       114



**testing the model with unknown data**

In [25]:
new_test = np.random.rand(5,6).ravel()
new_test

array([0.99015471, 0.26472276, 0.10841651, 0.99133204, 0.71037036,
       0.39341501, 0.82343041, 0.4544453 , 0.6906867 , 0.18563027,
       0.88371349, 0.25147095, 0.94031435, 0.27369555, 0.37483004,
       0.38295367, 0.73085422, 0.4235472 , 0.64230249, 0.83407279,
       0.37513442, 0.17467349, 0.49200317, 0.06963204, 0.68156623,
       0.30573166, 0.72965509, 0.66595469, 0.77692564, 0.75859367])

In [29]:
import warnings
warnings.filterwarnings('ignore')

In [30]:
new_test_pred = cls.predict([new_test])

In [32]:
new_test_pred[0]

1

In [33]:
if new_test_pred[0] == 0:
  print('M')
else:
  print('B')

B
